/** Korte uitleg bij de functies uit de les, voor in de dropdown. */
export const FUNCTION_HELP: Record<string, string> = {
  SOM: 'Telt alle getallen op',
  GEMIDDELDE: 'Rekenkundig gemiddelde',
  MEDIAAN: 'Middelste waarde',
  MIN: 'Kleinste waarde',
  MAX: 'Grootste waarde',
  AFRONDEN: 'Rondt af op een aantal decimalen',
  AANTALARG: 'Telt niet-lege cellen',
  AANTAL: 'Telt cellen met een getal',
  ALS: 'Voorwaarde: als ... dan ... anders',
  'AANTAL.ALS': 'Telt cellen die aan een voorwaarde voldoen',
  'X.ZOEKEN': 'Zoekt een waarde op en geeft het resultaat uit een ander bereik',
  'VERT.ZOEKEN': 'Zoekt in de eerste kolom van een tabel',
  'SOM.ALS': 'Telt alleen de waarden op die aan een voorwaarde voldoen',
  'GEMIDDELDE.ALS': 'Gemiddelde van de waarden die aan een voorwaarde voldoen',
  GROOTSTE: 'Het k-de grootste getal',
  KLEINSTE: 'Het k-de kleinste getal',
  BET: 'Betaling per periode van een lening of spaarplan',
  LINKS: 'Eerste tekens van een tekst',
  RECHTS: 'Laatste tekens van een tekst',
  DEEL: 'Tekens uit het midden van een tekst',
  LENGTE: 'Aantal tekens',
  HOOFDLETTERS: 'Zet tekst om in hoofdletters',
  'KLEINE.LETTERS': 'Zet tekst om in kleine letters',
  TEKST: 'Getal naar tekst met een notatie, bv. "00"',
};
